// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOhPFjUyUM3bpbilxUfVl-Wyz4MoitH4',
    appId: '1:41099816563:web:5051a95e4d7eb00a7f0406',
    messagingSenderId: '41099816563',
    projectId: 'heeey-8520d',
    authDomain: 'heeey-8520d.firebaseapp.com',
    storageBucket: 'heeey-8520d.firebasestorage.app',
    measurementId: 'G-PY9R0J2J5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkj7C9UlOeWyq-K3NGGkK2vPfNZVqd0ns',
    appId: '1:41099816563:android:d74e72c34acbcf987f0406',
    messagingSenderId: '41099816563',
    projectId: 'heeey-8520d',
    storageBucket: 'heeey-8520d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Q_0B5pYQQiRFEebW_5ijTHFLrD9nRbY',
    appId: '1:41099816563:ios:e6f8af8c0d4a82347f0406',
    messagingSenderId: '41099816563',
    projectId: 'heeey-8520d',
    storageBucket: 'heeey-8520d.firebasestorage.app',
    iosBundleId: 'com.example.heeey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Q_0B5pYQQiRFEebW_5ijTHFLrD9nRbY',
    appId: '1:41099816563:ios:e6f8af8c0d4a82347f0406',
    messagingSenderId: '41099816563',
    projectId: 'heeey-8520d',
    storageBucket: 'heeey-8520d.firebasestorage.app',
    iosBundleId: 'com.example.heeey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxOhPFjUyUM3bpbilxUfVl-Wyz4MoitH4',
    appId: '1:41099816563:web:9f63d9930448d0737f0406',
    messagingSenderId: '41099816563',
    projectId: 'heeey-8520d',
    authDomain: 'heeey-8520d.firebaseapp.com',
    storageBucket: 'heeey-8520d.firebasestorage.app',
    measurementId: 'G-G1ZRETGFWC',
  );
}
