name: CI/CD

on:
  push:
    branches: [ "main" ]
    # If you want to restrict which folders trigger the workflow, you can do:
    # paths:
    #   - 'web/**'
    #   - 'mobile/**'
    #   - 'lib/**'
    #   - '!some-other-folder/**'
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------
  # 1. Build & Deploy Admin
  # -------------------------
  build-and-deploy-admin:
    name: Build & Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build admin for web
        run: flutter build web --target=lib/main_admin.dart

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # -------------------------
  # 2. Build Android
  # -------------------------
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # -------------------------
  # 3. Build iOS
  # -------------------------
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # If you haven't set up iOS code signing, use --no-codesign
      - name: Build iOS App
        run: flutter build ios --no-codesign

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
